login/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
	url(r'^$', views.login),
 	url(r'^logout/$', views.logout),
	url(r'^home/$', views.home, name='home'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('login.urls', namespace='login'))
]

login/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render


from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import auth
from django.conf import settings
from django.core.urlresolvers import reverse


def login(request):
        next = request.GET.get('next', '/home/')
        if request.method == "POST":
                username = request.POST['username']
                password = request.POST['password']
                user = authenticate(username=username, password=password)


                if user is not None:
                        if user.is_active:
                                auth.login(request, user)
#                               return HttpResponse("<h1>Loggedin</h1>")
                                return HttpResponseRedirect(next)
                        else:
                                return HttpResponse("Inactive user.")
                else:
                        return HttpResponseRedirect(settings.LOGIN_URL)
        return render(request, "login.html", {'redirect_to': next})

def logout(request):
        auth.logout(request)
        return HttpResponseRedirect(settings.LOGIN_URL)

#@login_required
def home(request):
        return render (request, "home.html")

login/templates/header_1.html
<!DOCTYPE html>
<html >
  <head>

<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;"><span style="font-family: 'Times New Roman', serif;"><span style="color: #ffffff;"><span style="font-size: 300%;">TechStop Tool Box - TSTB</span></span></span></p>
<p style="text-align: center;">&nbsp;</p>

<meta charset="UTF-8">
    <title>Login/Sign-In</title>
    
    {% load staticfiles %}      
    
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'
    %}" type='text/css/'>
    <meta name="viewport" content = "width+device-width,initial-scale=1.0">

   <!-- <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>-->

        <style type="text/css">
		html,
		body   {
			height:100%
			}
	</style>
    
  </head>
<body class="body" style="background-color:#ffffff">
	<div>
		{% block content%}
		{% endblock %}
	</div>
</body>
</html>

login/templates/home.html
<!DOCTYPE html>
<h1>You are sucessfully Loggedin</h1>

login/templates/home_1.html
{% extends "header.html" %}
{% block content %}

  <body>

    <div class="logmod">
  <div class="logmod__wrapper">
   <!-- <span class="logmod__close">Close</span> -->
    <div class="logmod__container">
      <ul class="logmod__tabs">
        <li data-tabtar="lgm-2"><a href="#">Login-User</a></li>
        <li data-tabtar="lgm-1"><a href="#">Login-Admin</a></li>
      </ul>
      <div class="logmod__tab-wrapper">
      <div class="logmod__tab lgm-1">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your Username and Password <strong>to Sign in</strong></span>
        </div>
        <div class="logmod__form">
          <form accept-charset="utf-8" action="#" class="simform">
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">Username*</label>
                <input class="string optional" maxlength="255" id="user-name" placeholder="Username" type="username" size="50" />
              </div>
            </div>
            <div class="sminputs">
              <div class="input string optional">
                <label class="string optional" for="user-pw">Password *</label>
                <input class="string optional" maxlength="255" id="user-pw" placeholder="Password" type="password" size="50" />
              </div>
            </div>
            <div class="simform__actions">
              <button onclick="myFunction()" id="demo" class="sumbit" name="commit" type="sumbit">Log In</button> <!--<input class="sumbit" name="commit" type="sumbit" value="Log in" readonly/>-->
            </div>

          </form>
        </div>
        <div class="logmod__alter">
          <div class="logmod__alter-container">

          </div>
        </div>
      </div>
      <div class="logmod__tab lgm-2">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your username and password <strong>to sign in</strong></span>
        </div>
        <div class="logmod__form">
          <form accept-charset="utf-8" action="#" class="simform">
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">UserName*</label>
                <input class="string optional" maxlength="255" id="user-name" placeholder="Username" type="username" size="50" />
              </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-pw">Password *</label>
                <input class="string optional" maxlength="255" id="user-pw" placeholder="Password" type="password" size="50" />
                                                                <span class="hide-password">Show</span>
              </div>
            </div>
            <div class="simform__actions">
              <input class="sumbit" name="commit" type="sumbit" value="Log In" readonly />
        </div>
          </form>
        </div>
        <div class="logmod__alter">
          <div class="logmod__alter-container">
          </div>
        </div>
       </div>
      </div>
    </div>
  </div>
</div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

        <script src="index.js"></script>

   <script>
function myFunction() {
        alert("Sucessfully Logged in");}
</script>


  </body>

{% endblock %}

login/templates/login.html
<!DOCTYPE html>
<html >
  <head>

<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;"><span style="font-family: 'Times New Roman', serif;"><span style="color: #ffffff;"><span style="font-size: 300%;">Tech-Stop</span></span></span></p>
<p style="text-align: center;">&nbsp;</p>

<meta charset="UTF-8">
    <title>Login/Sign-In</title>
   
   {% load staticfiles %} 
    
    <link rel="stylesheet" href="{% static 'normalize.css' %}">

    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>

        <link rel="stylesheet" href="{% static 'style.css' %}">

    
  </head>

  
  <body>
     <form method="post" action="{% url 'login:home' %}">
{% csrf_token %}
    
    <div class="logmod">
  <div class="logmod__wrapper">
   <!-- <span class="logmod__close">Close</span> -->
    <div class="logmod__container">
      <ul class="logmod__tabs">
        <li data-tabtar="lgm-2"><a href="#">Login-User</a></li>
        <li data-tabtar="lgm-1"><a href="#">Login-Admin</a></li>
      </ul>
      <div class="logmod__tab-wrapper">
      <div class="logmod__tab lgm-1">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your Username and Password <strong>to Sign in</strong></span>
        </div>
        <div class="logmod__form">
          <form accept-charset="utf-8" action="#" class="simform">
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">Username*</label>
                <input class="string optional" maxlength="255" id="user-name" placeholder="Username" type="username" size="50" />
              </div>
            </div>
            <div class="sminputs">
              <div class="input string optional">
                <label class="string optional" for="user-pw">Password *</label>
                <input class="string optional" maxlength="255" id="user-pw" placeholder="Password" type="password" size="50" />
              </div>
            </div>
            <div class="simform__actions">
              <button onclick="myFunction()" id="demo" class="sumbit" name="commit" type="sumbit">Log In</button> <!--<input class="sumbit" name="commit" type="sumbit" value="Log in" readonly/>-->
            </div>

          </form>
        </div> 
        <div class="logmod__alter">
          <div class="logmod__alter-container">
              
          </div>
        </div>
      </div>
      <div class="logmod__tab lgm-2">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your username and password <strong>to sign in</strong></span>
        </div> 
        <div class="logmod__form">
          <form accept-charset="utf-8" action="#" class="simform">
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-name">UserName*</label>
                <input class="string optional" maxlength="255" id="user-name" placeholder="Username" type="username" size="50" />
              </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <label class="string optional" for="user-pw">Password *</label>
                <input class="string optional" maxlength="255" id="user-pw" placeholder="Password" type="password" size="50" />
                						<span class="hide-password">Show</span>
              </div>
            </div>
            <div class="simform__actions">
              <input class="sumbit" name="commit" type="sumbit" value="Log In" readonly />
	</div> 
          </form>
        </div> 
        <div class="logmod__alter">
          <div class="logmod__alter-container">
          </div>
        </div>
          </div>
      </div>
    </div>
  </div>
</div>
    <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>

        <script src="{% static 'index.js' %}"></script>

   <script>
function myFunction() {
	alert("Sucessfully Logged in");}
</script>

 </form>
  </body>
</html>